### ISSUE TITLE
Wifidog not redirecting webpages properly

### ISSUE THREAD

**Issue by tgsigma** [mirror/dd-wrt#20]
Hi, please watch this issue, http://svn.dd-wrt.com/ticket/3344.

I tested the history builts with my tplink_tl-wr840nv1, and I find that: 
The latest wifidog usable build is 12/12/2013 ftp://ftp.dd-wrt.com/betas/2013/12-12-2013-r23082/.
The latest wifidog unusable build is 12/17/2013 ftp://ftp.dd-wrt.com/betas/2013/12-17-2013-r23138/. 

So, maybe some changes between 12/12/2013 and 12/17/2013 cause this issue.

Can some guys help to find it out?

Thanks,
Kai

**Comment by GXTX** [comment]
This repo isn't maintained by the DD-WRT devs, it's just a mirror of their SVN.

**Comment by tgsigma** [comment]
Thanks, I will issue a CR there.
