### ISSUE TITLE
 request for hosting the mirror

### ISSUE THREAD

**Issue by BrainSlayer** [mirror/dd-wrt#24]
i'm the author and maintainer of dd-wrt. if you would like to give the job into my hand, just do it

**Comment by jkldgoefgkljefogeg** [comment]
That would be great if you can host an official github repo. @john-peterson can add you to the org.

**Comment by GXTX** [comment]
*cough*

**Comment by jkldgoefgkljefogeg** [comment]
poke @john-peterson

**Comment by BrainSlayer** [comment]
the problem is that github has a repo quota even if github itself states that there is no quota. i already tried to clone our svn server, but it failed since the repositoriy size was to big

**Comment by jkldgoefgkljefogeg** [comment]
I had to use BFG to remove some large blobs from previous commits (current repo doesn't have those large blobs any more). Github has a hard 100MB per file limit.
https://help.github.com/articles/what-is-my-disk-quota/

**Comment by john-peterson** [comment]
Invitation sent

**Comment by BrainSlayer** [comment]
joined
