### ISSUE TITLE
DHCP reserved IP's

### ISSUE THREAD

**Issue by magnificu** [mirror/dd-wrt#32]
(Bug) If there are more than 4 entries in Services Static Leases the internet connection stops. If one of the entry is removed (3 entries in the list) the internet connection is back.

(Feature) To remove only the first entry of the list is not possible without removing all the previous entries. Please add the possibility to select which entry to be removed.

(all tests have been performed with r42847 build)

**Comment by BrainSlayer** [comment]
ensure you have no typo like missing lease time etc. i tested 20 entries. its working
