### ISSUE TITLE
Missing the check of cpu_has_dc_aliases

### ISSUE THREAD

**Issue by Lirong-source** [mirror/dd-wrt#37]
Hi, in [linux-3.10](https://github.com/mirror/dd-wrt/tree/master/src/linux/universal/linux-3.10), /arch/mips/mm/init.c, line 253, function *copy_from_user_page*, the kernel of dd-wrt deleted the check of cpu_has_dc_aliases (definition: ```#define cpu_has_dc_aliases	(cpu_data[0].dcache.flags & MIPS_CACHE_ALIASES)```), which is used to determine whether OS allows the alias of CPU cache. If yes, multiple virtual addresses can map to a single physical address, and using virtual addresses as tags may cause multiple copies of one piece of data in the cache. In this situation, if one of the copies is modified and the other copies are not updated simultaneously, the data will lose its integrity, which will lead to program errors. Therefore, this security check can ensure the data integrity of a program and should not be deleted.

**Comment by BrainSlayer** [comment]
i dont know what you are talking about. the check is there and not removed
