### ISSUE TITLE
Use of invalid parameter

### ISSUE THREAD

**Issue by Lirong-source** [mirror/dd-wrt#38]
Hi, in [linux-3.10](https://github.com/mirror/dd-wrt/tree/master/src/linux/universal/linux-3.10) and [linux-3.18](https://github.com/mirror/dd-wrt/tree/master/src/linux/universal/linux-3.18) /drivers/usb/core/hub.c, line 4367, function hub_port_init, the kernel of dd-wrt deleted the check for hub->tt.hub, which is a check for the existence of upstream high-speed hub and such missing check will leads to the use of invalid parameter.

**Comment by BrainSlayer** [comment]
there is no check removed in dd-wrt which is present in the upstream kernel on that line or code

**Comment by BrainSlayer** [comment]
you should also consider quirks for special devices like broadcom
