### ISSUE TITLE
Any example how to use ndpi-netfilter to block Bittorrent traffic?

### ISSUE THREAD

**Issue by houmie** [mirror/dd-wrt#380]
Hi @BrainSlayer 

Is there any example how to use your netfilter (dd-wrt/tree/master/src/router/ndpi-netfilter/ndpi-netfilter) to block bittorrent traffic on a server?

Much appreciated,
Houman

**Comment by BrainSlayer** [comment]
if you patched iptables for supporting the ndpi module. its simple. iptables .... -m ndpi --proto bittorrent -j REJECT. 

replace ... with any other filter options. a full list of all protocols can be found in src/router/iptables-new/extensions/libxt_ndpi.c
