### ISSUE TITLE
Data race problem

### ISSUE THREAD

**Issue by Lirong-source** [mirror/dd-wrt#40]
Hi, in  [linux-3.18](https://github.com/mirror/dd-wrt/tree/master/src/linux/universal/linux-3.18), drivers/net/phy/at803x.c, line 255, function  at803x_resume, function phy_write is called without the protection of mutex_lock and mutex_unlock.

**Comment by BrainSlayer** [comment]
resume is not race sensitive, since device no function is called or used before call of resume. only suspend must be locked
