### ISSUE TITLE
R7800 

### ISSUE THREAD

**Issue by redblue-pkt** [mirror/dd-wrt#443]
Hello
I have random restarts on the Netgear R7800 with Linux kernel 6.1.80 revision r55363. Kernel 4.9 revision r48352 everything ok. What information do you need?

**Comment by BrainSlayer** [comment]
check the latest revisions. there is some progress on it. unfortunatly its very hard to reproduce it. its helpfull if there is any full serial log when it happens.

**Comment by BrainSlayer** [comment]
i fixed several crash causes in the kernel the last days. so i hope it will work better in the next builds
