### ISSUE TITLE
USB3-LAN-Adapter (ax88179_178a)   Driver  still not included in 57605

### ISSUE THREAD

**Issue by flood404** [mirror/dd-wrt#447]
Sp!derman  USB adapter is still not working.  The driver isn't included named AX88179_178A.ko       It wasn't readded with this https://svn.dd-wrt.com/changeset/57605

He also had an issue where it was not detected automatically on releases with the driver and had to load the driver manually.

**Comment by BrainSlayer** [comment]
yes i found it by myself
