### ISSUE TITLE
nvram settings for regulatory domain don't match GUI

### ISSUE THREAD

**Issue by slycordinator** [mirror/dd-wrt#45]
The website configuration allows for setting a singe regulatory domain for wlan0. You cannot set the regdomain for any secondary radio, which is reasonable. But the subsequent nvram settings don't always match this.

Steps to REPRO:
1) Flash with a ddwrt firmware
2) Change the regdomain in the GUI to a different country from its default
3) commit nvram settings
4) See that wlan0_regdomain="$NEW_COUNTRY" and wlan1_regdomain="$OLD_COUNTRY"

In my GUI:
"Regulatory Domain = KOREA_REPUBLIC" [because I live in South Korea (Republic of Korea)]

NVRAM SETTINGS:
wlan0_regdomain=KOREA_REPUBLIC
wlan1_regdomain=UNITED_STATES

ACTUAL RESULTS:
regdomains for wlan0 and wlan1 are different from each other

EXPECTED RESULTS:
1) There be only one variable, since it's redundant to store multiple settings that are intended to be identical.

or

2) The two variables to be set identically to each other to both match the GUI

Device info:
TP-Link ARCHER-C7 v2 (US)

![brave_Bw8hkmlmJK](https://user-images.githubusercontent.com/68940237/132927433-9888904d-0a48-4063-99fe-315934ba30f9.png)
![screen](https://user-images.githubusercontent.com/68940237/132927640-84970ac0-31df-4314-b9d4-3b1e7a3e0038.png)

**Comment by BrainSlayer** [comment]
there is just one setting. only wlan0_regdomain is used

**Comment by slycordinator** [comment]
"there is just one setting. only wlan0_regdomain is used" 

Imo, it seems to default to generating two settings, only one of which is used.

**Comment by BrainSlayer** [comment]
the wlan1_default is orphan on obsolete. or lets say on some older platforms it was possible to run 2 different reg domains. but this isnt the case for mac80211 based drivers
